---
title: "Pipeline:4-RNA-seq and a minimal RNA-seq cook book"
author: "Rishi Das Roy, Postdoctoral Fellow, Evo-Devo lab, University of Helsinki"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
description: "This is a minimal example of how to process RNA-seq"
---

# Preface {-}

The high throughput RNA-sequencing technology has been widely used and has advanced our understanding of RNA biology. The process of RNA-sequencing can be divided in two parts; 1) Generating the data from biological sample and 2) Computational data analysis. This book is about the second part which is usually done with a subset of many related software, refered as pipeline. For ease of biologist, there are many predefined   and I have been analyzing RNA-seq data from 2014 using different. This book is an attempt to describe how to use the pipeline [4-RNA-seq](https://github.com/vondoRishi/4-RNA-seq) and it is also a collection of the study materials which has been used in RNA-seq section of the course [Advanced course in genomics and gene regulation 2019](https://moodle.helsinki.fi/course/view.php?id=31702) by me. 

## Structure of the book {-}
 Chapter 1 and 2 explains the step wchich are executed from a unix terminal. Chapter 3 describes the final data analysis step which requires R and can be performed in any OS. Chapter 4 explains 4-RNA-seq pipleline which to execute chapter 1 and 2 commands in easier and efficient ways. Therefore chapter 1 to 3 is must for beginner and chapter 4 is for who have slurm environment and looking for a pipeline to execute RNA-seq data.

### Chapter 1: Quality Control {-}
Description of quality assessment, filtering ribosomal RNA and bad reads of fastq files with fastqc, multiqc, sortmerna and trimmomatic.  

### Chapter 2: Alignment and count {-}
Alighnment of reads and count values from fastq and bam files using toll like star and htseq-count. 

### Chapter 3: Read count analysis {-}
Differential expression analysis with R package DESeq2.  

### Chapter 4: Pipeline:4-RNA-seq {-}
A step by step instruction for 4-RNA-seq pipeline execution.  


## Acknowledgement  {-}

Most of the study material are motivated from **[Rna-seq data analysis, Workshop II](http://www.finbionet.fi/ils/ngg2016/ws_ngg.html)** 1-3.11.2016. 
This could not be possible without the encouragement and permission from the istructor/author of the workshop. I like to thank  
* Nicolas DelHomme, Umeå University, Sweden  
* Bastian Schiffthaler, Umeå University, Sweden  
* Charlotte Soneson, Friedrich Miescher Institute for Biomedical Research  
* Petri Törönen, University of Helsinki for reviewing this book. 


The online version of this book is licensed under the [Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License](http://creativecommons.org/licenses/by-nc-sa/4.0/).